const images = [
  {
    src: "images/2022/organizers/CaseIT-OC-emily.jpg",
    name: "Emily Kim",
    position: "Chair",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-rachel.jpg",
    name: "Rachel Dee",
    position: "Vice Chair of Competition Execution",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-rachelv.jpg",
    name: "Rachel Vicencio",
    position: "Vice Chair of Marketing",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-megan.jpg",
    name: "Megan Wong",
    position: "Director of Logistics",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-lizzy.jpg",
    name: "Elizabeth Teefel",
    position: "Director of Logistics",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-wayne.jpg",
    name: "Wayne Yan Muk",
    position: "Director of Events",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-jodi.jpg",
    name: "Jodi Tabuchi",
    position: "Director of Competitor Experience",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-henry.jpg",
    name: "Henry Ngyuen",
    position: "Director of Technology",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-michelle.jpg",
    name: "Michelle Kang",
    position: "Director of Finance",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-ali.jpg",
    name: "Ali Leung",
    position: "Director of University Relations",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-russell.jpg",
    name: "Russell Kwok",
    position: "Director of Corporate Relations",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-tejas.jpg",
    name: "Tejas Gandesha",
    position: "Director of Corporate Relations",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-bita.jpg",
    name: "Bita Zojaji",
    position: "Director of Internal Strategy",
    team: "",
  },
  // {
  //   src: "images/2022/organizers/CaseIT-OC-daniel.jpg",
  //   name: "Test",
  //   position: "position",
  //   team: "",
  // },
  {
    src: "images/2022/organizers/CaseIT-OC-maya.jpg",
    name: "Maya Ramadhina",
    position: "Director of Design",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-andrea.jpg",
    name: "Andrea Chan",
    position: "Director of Content Strategy",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-russellee.jpg",
    name: "Russellee Santos",
    position: "Logistics Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-simrit.jpg",
    name: "Simrit Dhaliwal",
    position: "Events Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-braden.jpg",
    name: "Braden Lo",
    position: "Competitor Experience Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-johnson.jpg",
    name: "Johnson Ngo",
    position: "Technology Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-paul.jpg",
    name: "Paul Lee",
    position: "Corporate Relations Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-bryan.jpg",
    name: "Bryan Li",
    position: "Media Associate",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-neva.jpg",
    name: "Neva Hoang",
    position: "Design Associate",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-james.jpg",
    name: "James Duong",
    position: "Design Associate",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-vanessa.jpg",
    name: "Vanessa Chau",
    position: "Team Host",
    team: "",
  },
  // {
  //   src: "images/2022/organizers/CaseIT-OC-brandon.jpg",
  //   name: "Test",
  //   position: "position",
  //   team: "",
  // },
  {
    src: "images/2022/organizers/CaseIT-OC-kristy.jpg",
    name: "Kristy Hong",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-lawrence.jpg",
    name: "Lawrence Zhu",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-jacky.jpg",
    name: "Jacky Chen",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-selena.jpg",
    name: "Selena Situ",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-brandonxu.jpg",
    name: "Brandon Xu",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-jarl.jpg",
    name: "Jarl Arciaga",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-mihee.jpg",
    name: "Mi Hee Hashimoto Chang",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-yeelong.jpg",
    name: "Yee Loong Tang",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-kenneth.jpg",
    name: "Kenneth Jiang",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-ryan.jpg",
    name: "Ryan Maclean",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-christina.jpg",
    name: "Christina Cao",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-caeleigh.jpg",
    name: "Caeleigh Cardwell",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-aliya.jpg",
    name: "Aliya Hussein",
    position: "Team Host",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-emilysu.jpg",
    name: "Emily Su",
    position: "PIVOT Chair",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-douglas.jpg",
    name: "Douglas Cheung",
    position: "PIVOT Director of External Relations",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-melissa.jpg",
    name: "Melissa Bouwmeester",
    position: "PIVOT Director of Marketing",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-justin(1).jpg",
    name: "Justin Jung",
    position: "PIVOT Coordinator",
    team: "",
  },
  {
    src: "images/2022/organizers/CaseIT-OC-esther.jpg",
    name: "Esther Ng",
    position: "PIVOT Coordinator",
    team: "",
  },
]

export default images
