const images = [
  "images/[Chair]_Jordan.png",
  "images/[VC]_Jenny.png",
  "images/[VC]_Kyle.png",
  "images/[AcademicDirector]_Simon Ford.png",
  "images/[SEDO]_Hansel Wu.png",
  "images/[Director]_Ahmad.png",
  "images/[Director]_Alicia.png",
  "images/[Director]_Alvin.png",
  "images/[Director]_Amena.png",
  "images/[Director]_Annie.png",
  "images/[Director]_Cody.png",
  "images/[Director]_Denzel.png",
  "images/[Director]_Donovan.png",
  "images/[Director]_Emily.png",
  "images/[Director]_Jay.png",
  "images/[Director]_Joaquin.png",
  "images/[Director]_Sid.png",
  "images/[Director]_Vanessa.png",
  "images/[Director]_Henry.png",
  "images/[Associate]_Diana.png",
  "images/[Associate]_Jasmeet.png",
  "images/[Associate]_Olivia.png",
  "images/[Coordinator] Kelly.png",
  "images/[Coordinator] Tejas.png",
  "images/[Coordinator]_Alicia.png",
  "images/[Coordinator]_Emily S.png",
  "images/[Coordinator]_Gurbir.png",
  "images/[Coordinator]_Lily.png",
  "images/[Coordinator]_Max.png",
  "images/[TeamHost]_Ali.png",
  "images/[TeamHost]_Ashley.png",
  "images/[TeamHost]_Ben.png",
  "images/[TeamHost]_Bita.png",
  "images/[TeamHost]_Brandon.png",
  "images/[TeamHost]_Jessica.png",
  "images/[TeamHost]_Jodi.png",
  "images/[TeamHost]_Lizzy.png",
  "images/[TeamHost]_Luca.png",
  "images/[TeamHost]_Manraj.png",
  "images/[TeamHost]_Megan.png",
  "images/[TeamHost]_Melissa.png",
  "images/[TeamHost]_Naomi.png",
  "images/[TeamHost]_Russell.png",
  "images/[TeamHost]_Scott.png",
  "images/[TeamHost]_Shah.png",
]

export default images;